const TEXT = 'TEXT'
const NAME = 'VARCHAR(255)'
const DATE = 'DATE'
const CHAR1 = 'CHAR(1)'
const CHAR2 = 'CHAR(2)'
const CHAR8 = 'CHAR(8)'
const EMAIL = 'VARCHAR(50)'
const PHONE = 'VARCHAR(30)'
const MONEY = 'NUMERIC(15,2)'
const STRING = 'VARCHAR(255)'
const SELECT = 'VARCHAR(25)'
const BOOLEAN = 'BOOLEAN'
const INTEGER = 'INTEGER'
const CPFCNPJ = 'VARCHAR(14)'
const PERCENT = 'NUMERIC(15,8)'
const PRIMARY = 'SERIAL NOT NULL'
const DATETIME = 'TIMESTAMP'
const REFERENCES = 'REFERENCES'

export default {
  TEXT,
  DATE,
  NAME,
  CHAR1,
  CHAR2,
  CHAR8,
  EMAIL,
  PHONE,
  MONEY,
  STRING,
  SELECT,
  BOOLEAN,
  INTEGER,
  CPFCNPJ,
  PERCENT,
  PRIMARY,
  DATETIME,
  REFERENCES
}
